#!/bin/bash
set -e

PROJECT_TYPE="${PROJECTTYPE:-base}"
INSTALL_SKILLS="${INSTALLSKILLS:-true}"
HUB_URL="${HUBURL:-http://host.docker.internal:8420}"

echo "[claude-hive] Installing Claude Hive Feature (project_type=${PROJECT_TYPE})..."

# Install Claude Code CLI if not present
if ! command -v claude &> /dev/null; then
    echo "[claude-hive] Installing Claude Code CLI..."
    npm install -g @anthropic-ai/claude-code
fi

# Install hive-agent if not present (WebSocket client of the hub since M4).
if ! command -v hive-agent &> /dev/null; then
    echo "[claude-hive] Installing hive-agent..."
    pip install hive-agent 2>/dev/null || pip3 install hive-agent 2>/dev/null || true
fi

# Set up environment variables (no ANTHROPIC_API_KEY — uses Max plan subscription auth).
# HIVE_AUTH_TOKEN must be provided by the outer environment (passed via
# devcontainer.json remoteEnv from the host's token) — we don't write it
# into /etc/environment because this file is readable by every user in
# the container.
cat >> /etc/environment <<EOF
HIVE_HUB_URL=${HUB_URL}
EOF

# Guard against API key contamination in shell profiles
for PROFILE in /root/.bashrc /root/.zshrc /etc/bash.bashrc; do
    if [ -f "$PROFILE" ]; then
        cat >> "$PROFILE" <<'GUARD'

# Claude Hive: unset API key to enforce Max plan subscription auth
if [ -n "$ANTHROPIC_API_KEY" ]; then
    echo "[claude-hive] WARNING: Unsetting ANTHROPIC_API_KEY to use Max plan subscription auth"
    unset ANTHROPIC_API_KEY
fi
GUARD
    fi
done

# Create .claude directory structure (may already exist from shared volume)
CLAUDE_DIR="${HOME}/.claude"
mkdir -p "${CLAUDE_DIR}/skills"
mkdir -p "${CLAUDE_DIR}/agents"
mkdir -p "${CLAUDE_DIR}/hooks"
mkdir -p "${CLAUDE_DIR}/rules"

# Install default settings.json if not present
if [ ! -f "${CLAUDE_DIR}/settings.json" ]; then
    cat > "${CLAUDE_DIR}/settings.json" <<'SETTINGS'
{
    "permissions": {
        "allow": [
            "Bash(git *)",
            "Bash(python *)",
            "Bash(pytest *)",
            "Bash(pip *)",
            "Bash(uv *)",
            "Bash(gh *)",
            "Bash(hive-agent *)",
            "Bash(npm *)",
            "Bash(node *)",
            "Read",
            "Write",
            "Edit",
            "Glob",
            "Grep"
        ]
    }
}
SETTINGS
fi

# Inspect the bootstrapper-generated skills manifest (if present in the
# workspace) so we can report what Claude Hive expects to install. The
# manifest is generated by bootstrapper/provision.py at provision time;
# actual skill-file materialization is performed separately by the
# hub on first container start.
WORKSPACE_MANIFEST="${WORKSPACE_FOLDER:-/workspaces}"
# Search the workspace tree shallowly for the manifest (max depth 3).
MANIFEST_FILE="$(find "${WORKSPACE_MANIFEST}" -maxdepth 3 -type f -name skills_manifest.json 2>/dev/null | head -n1)"
if [ -n "${MANIFEST_FILE}" ] && [ -f "${MANIFEST_FILE}" ]; then
    SKILL_COUNT="$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(len(d.get('skills',[])))" "${MANIFEST_FILE}" 2>/dev/null || echo 0)"
    PTYPE="$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(d.get('project_type',''))" "${MANIFEST_FILE}" 2>/dev/null || echo unknown)"
    echo "[claude-hive] Skills manifest detected (project_type=${PTYPE}, ${SKILL_COUNT} skill(s) declared)."
    # Mark the manifest as seen so the hub can skip duplicate work.
    touch "${CLAUDE_DIR}/.skills_manifest_seen"
else
    echo "[claude-hive] No skills manifest found — provision the workspace via the hub to populate one."
fi

echo "[claude-hive] Claude Hive Feature installed successfully."
