"""baseline registry schema

Revision ID: 80a461aca9bf
Revises:
Create Date: 2026-04-17 02:11:13.879115+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80a461aca9bf"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "containers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_folder", sa.Text(), nullable=False),
        sa.Column("project_type", sa.Text(), server_default="base", nullable=False),
        sa.Column("project_name", sa.Text(), nullable=False),
        sa.Column("project_description", sa.Text(), server_default="", nullable=False),
        sa.Column("git_repo_url", sa.Text(), nullable=True),
        sa.Column("container_id", sa.Text(), nullable=True),
        sa.Column("container_status", sa.Text(), server_default="unknown", nullable=False),
        sa.Column("agent_status", sa.Text(), server_default="unreachable", nullable=False),
        sa.Column("agent_port", sa.Integer(), server_default="9100", nullable=False),
        sa.Column("has_gpu", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("has_claude_cli", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("claude_cli_checked_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_folder"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("containers")
    # ### end Alembic commands ###
